# Do as following:
#  - create ~/.wakatime.cfg as the following config: (see wakatime top page)
#    [settings]
#    api_key = <key generated by webui>
#    api_url = <url(http://localhost:(forward port))>/api/v1/users/current/heartbeats.bulk
#  - install each editors plugins.
#    vscode: WakaTime(WakaTime.vscode-wakatime)
#    chrome: WakaTime(jnbbnacmeggbgdjgaoojpmhdlkkpblgi)
{ config, pkgs, lib, ... }:
let
  cfg = config.my.system.worklog;
in {
  options.my.system.worklog = {
    enable = lib.mkEnableOption "Whether to enable worklog.";
    port = lib.mkOption {
      type = lib.types.port;
      description = "Port for worklog server.";
      default = 3000;
    };
    host = lib.mkOption {
      type = lib.types.str;
      description = "Host for worklog sever.";
      default = "localhost";
    };
    publicUrl = lib.mkOption {
      type = lib.types.str;
      description = "Public URL for worklog sever.";
      default = "http://${cfg.host}:${toString cfg.port}";
    };
    settings = lib.mkOption {
      type = lib.types.attrs;
      description = "Settings for worklog";
      default = {};
    };
    environmentFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
    };
  };

  config = lib.mkIf cfg.enable {
    services.wakapi = {
      enable = true;
      package = pkgs.wakapi;
      database = {
        dialect = "sqlite3";
        createLocally = lib.mkForce false;
      };
      environmentFiles = [
        (pkgs.writeText "" ''
          WAKAPI_PASSWORD_SALT="WGgYPNa4B4sfgJK3p61TYgWkx44rjTUY"; # wakapi github sample. This is insecure
        '')
        cfg.environmentFile
      ];
      settings = {
        server = {
          listen_ipv4 = cfg.host;
          port = cfg.port;
          public_url = cfg.publicUrl;
        };
        security = {
          invite_codes = false;
          disable_frontpage = true;
        };
        mail.enable = false;
      } // cfg.settings;
    };
  };
}
